### ISSUE TITLE
Incompatible with python 3.10.0 (UPDATED)

### ISSUE THREAD

**Issue by itsrxmmy** [brentvollebregt/auto-py-to-exe#205] opened 2021-10-18 02:42 UTC
I got this issue with auto-py-to-exe and i noticed it uses pyinstaller, so i tried pyinstaller (and yes my pip and pyinstaller were up to date) and pyinstaller had the exact same error; 

```
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1711, in _find_head_package
    raise ImportError("No module named " + target_package_name)
ImportError: No module named _bootlocale

Project output will not be moved to output folder
Complete.
```

which means its not an issue with auto-py-to-exe, but an issue with pyinstaller. so unfortunately you guys cant do anything about it, just thought id let you know

**Comment by madtatu-development** [comment] 2021-11-02 10:28
oh, so funding is an issue again? because it had been solved in july (PyInstaller is no longer in urgent need of funding, having an active volunteer development team (@Legorooj, @bwoodsend, @rokm).): 

https://github.com/pyinstaller/pyinstaller/issues/4404

regarding to the bootlocal issue, some extra information:

https://github.com/pyinstaller/pyinstaller/issues/5693

and if someone ran into the same problem I did (IndexError: tuple index out of range):

https://github.com/pyinstaller/pyinstaller/issues/6301

**Comment by Legorooj** [comment] 2021-11-02 15:05
Funding on PyInstaller is not an issue currently. Not been an issue for many months now (way before July actually, just didn't think to close that ticket till then.)

As for Python 3.10, it's supported now (v4.6+) - though there are indeed a few bugs. pyinstaller/pyinstaller#6301 is a bug in CPython not PyInstaller.

**Comment by madtatu-development** [comment] 2021-11-02 18:50
@Legorooj : Awesome, thanks for the heads up from first hand! 
@brentvollebregt : Since its confirmed that pyinstaller support Python 3.10, any chance you could have a look at it ?

BIG thanks to all of you !!

**Comment by bwoodsend** [comment] 2021-11-02 23:58
> As for Python 3.10, it's supported now (v4.6+) - though there are indeed a few bugs. pyinstaller/pyinstaller#6301 is a bug in CPython not PyInstaller.

I really would like to emphasise that issue though. With it I'd honestly say that we don't yet support Python 3.10.

**Comment by madtatu-development** [comment] 2021-11-03 10:21
Oh, I see, Thank you for the clarification. The we hold tight and fingers crossed!

**Comment by brentvollebregt** [comment] 2021-11-03 12:01
Thanks, heaps for coming over guys - I hadn't noticed PyInstaller 4.6 was released a few days ago.

I'll get PyInstaller 4.6 into auto-py-to-exe as there are new arguments that need to be categorised.

**Comment by madtatu-development** [comment] 2021-11-03 12:32
@brentvollebregt 

Thanks to Your amazing support !!!!!!!!

One more thing: I am not sure it is related, but allow me to report it here as it is "new": 

Background:
- after I couldnt create the EXE after updating to Python 3.10,0, I had decided to go back to 3.9.7
- since I am using ssd image base backup, I simply restored an earlier OS image where python wasnt installed at all to ensure there is no garbage left e.g. from an uninstall proces.
- I installed python 3.9.7 x64 on windows 10 latest version, just as it was before. 

Problem:
- for some reason, the EXACT SAME code with the EXACT same json settings file, which was perfectly compiled to exe and executed earlier, now, throws the following error during execution:
ImportError: Module 'pythoncom' isn't in frozen sys.path ['C:\\Users\\Master\\AppData\\Local\\Temp\\_MEI47642\\base_library.zip', 'C:\\Users\\Master\\AppData\\Local\\Temp\\_MEI47642\\lib-dynload', 'C:\\Users\\Master\\AppData\\Local\\Temp\\_MEI47642']

- All required dirs are added. 
- All modules and submodules are imported. 
- Cache emptied. 

Still not work. what previously worked like a charm. 

- I am sure the problem is on my side, eventhough it is same evironment, code and process, but there is no miracle, something must had been changed what i overlook otherwise it would not give an error. 

May I ask if you could guide me, what he heck could be the problem ?

**Comment by brentvollebregt** [comment] 2021-11-04 08:07
@madtatu-development could you create a new issue for this? Keeping each issue in their own GitHub issue helps keep things on track and stops people from getting notified about something not on topic.

**Comment by brentvollebregt** [comment] 2021-11-04 08:10
auto-py-to-exe 2.11.0 has just been released to PyPI which contains support for PyInstaller 4.6 🎉

**Comment by madtatu-development** [comment] 2021-11-04 09:45
> @madtatu-development could you create a new issue for this? Keeping each issue in their own GitHub issue helps keep things on track and stops people from getting notified about something not on topic.

Sure thing! I just wasnt sure if this problem is related to this or not, so I thought if it is separate, github allows you to move it as new issue. Create it right away, sorry for the trouble.

**Comment by madtatu-development** [comment] 2021-11-04 09:45
> auto-py-to-exe 2.11.0 has just been released to PyPI which contains support for PyInstaller 4.6 🎉

You are SUPER AWESOME! BIG THANKS !!!!!!!!!!

**Comment by bwoodsend** [comment] 2022-01-04 08:18
You can probably close this now anyway. Python 3.10.1 contained a fix for the tuple index issue so we're good to go.

**Closed** 2022-01-08 10:16 UTC
