### ISSUE TITLE
File not found when ran as exe

### ISSUE THREAD

**Issue by ghost** [brentvollebregt/auto-py-to-exe#73] opened 2019-09-29 23:04 UTC
say i'm trying to read from .txt file.

`with open( 'file', 'r' ) as file:
         for line in file.readlines()
               print(  line  )`

It'll say that 'file' does not exist, but if run the same code in Spyder or PyCharm it will run fine

**Comment by brentvollebregt** [comment] 2019-09-30 10:14
If you're referencing the file relatively to the project, have you added the file you're referencing as an additional file?

**Comment by CodeNameGhost** [comment] 2019-10-01 13:22
Oh I don’t think so, think I was added the folders instead lol. I’ll try
that, thanks

**Comment by CodeNameGhost** [comment] 2019-10-01 20:08
Getting same issue, when trying to open data from another file it says No such file or directory -> 'C:\\Users\\User\\AppData\\Local\\Temp\\_MEI168562\\THEMAINDIR\\SUBDIR\\SUBDIR2'

Even after adding additional folders. 'THEMAINDIR\\SUBDIR\\SUBDIR2'.

It works in the IDE but not as exe.

**Comment by brentvollebregt** [comment] 2019-10-02 02:57
In the [debugging help I provide](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/#debugging), I state that you should use one directory mode when debugging as it makes it a lot easier to see what's in the output structure.

When using one directory mode, are the files you're trying to access present? You can locate them in the output directory.

**Comment by CodeNameGhost** [comment] 2019-10-06 18:08
Yeah the folder is in the output dir, but it renames the the with and 'i' and the beginning of the name... like the folder is added as an additional too.

Actual folder name: Quar.
Error Output: No such file or directory iQuar.

**Comment by brentvollebregt** [comment] 2019-10-06 19:16
Can you please supply the command that is shown at the bottom of the UI (asked in my first reply)

**Comment by CodeNameGhost** [comment] 2019-10-06 21:47
pyinstaller -y -i "C:/Users/User/OneDrive/Desktop/Hopstarter-Malware-Search.ico" --add-data "C:/Users/User/OneDrive/Desktop/Antimalware X/poison/iQUAR";"iQUAR/"  "C:/Users/User/OneDrive/Desktop/Antimalware X/127Sec.py"

**Comment by brentvollebregt** [comment] 2019-10-06 22:16
The section

> "C:/Users/User/OneDrive/Desktop/Antimalware X/poison/iQUAR";"iQUAR/"

shows that you have specified for the `iQUAR` folder to be put into the `iQUAR/` directory. Is this not what you have specified in the UI?

**Comment by CodeNameGhost** [comment] 2019-10-06 22:19
no i was just adding the folder to see if it would work

**Comment by brentvollebregt** [comment] 2019-10-06 22:22
What are you expecting to happen? You have specified that the folder is copied to the `iQUAR` directory, why would it then be put it `Quar` when you have not told it to be copied there?

**Comment by CodeNameGhost** [comment] 2019-10-06 22:22
So if i don't add that folder and an additional i still get 

> No such file or directory: 'C:\\Users\\User\\output\\127Sec\\poison\\iiQUAR\\susmalware'
----> iiQUAR doesn't exist because there is no directory named iiQUAR, only iQUAR.

**Comment by CodeNameGhost** [comment] 2019-10-06 22:25
My goal is too move files into iQUAR\susmalware directory... but when turned into an exe the programs doesn't work, but will work fine in the ide.

**Comment by brentvollebregt** [comment] 2019-10-06 22:25
In the command you have shown me, you've told the application to copy the folder to `iQUAR/`. Why do you then expect it to be copied to `iiQUAR` when you have explicitly told it to copy to `iQUAR/`?

**Comment by CodeNameGhost** [comment] 2019-10-06 22:28
In my project there is no folder named 'iiQUAR', only with a single 'i'. 
So idk where it's getting 'C:\Users\User\output\127Sec\poison\iiQUAR\susmalware' from when the actual path is 'C:\Users\User\output\127Sec\poison\iQUAR\susmalware'

**Comment by brentvollebregt** [comment] 2019-10-06 22:31
Can you please provide a **minimal** reproducible example of this and the command you use to bundle the exe? I do not want to see your whole script, just the section that can reproduce this issue.

**Comment by CodeNameGhost** [comment] 2019-10-06 22:35
Error starts here: `shutil.move( file, __file__[:-13]+'{}'.format( 'iQUAR\\susmalware' ) )`

One directory mode:  > pyinstaller -y -i "C:/Users/User/OneDrive/Desktop/Hopstarter-Malware-Search.ico"  "C:/Users/Users/OneDrive/Desktop/Antimalware X/127Sec.py"

**Comment by brentvollebregt** [comment] 2019-10-06 22:37
That command does not include the copying of files/directories whatsoever and can you please give a minimal reproducible example (that actually runs), not just one line.

**Comment by CodeNameGhost** [comment] 2019-10-06 22:42
yeah i can, the thing is that the directory iQUAR is built into the exe, so it's not just a random made folder on the desktop or something.

**Comment by brentvollebregt** [comment] 2019-10-07 20:39
I cannot help if I cannot reproduce this situation myself. 

Please provide a minimal reproducible example of what you are trying to do that demonstrates the `iiQUAR` folder creation.

**Comment by brentvollebregt** [comment] 2019-10-20 10:18
It seems like "Billy" deleted their account so I don't imagine this will be getting resolved. Closing due to this reason.

**Closed by brentvollebregt** 2019-10-20 10:18 UTC
