### ISSUE TITLE
Infinite initialization when trying to import config

### ISSUE THREAD

**Issue by kapertdog** [brentvollebregt/auto-py-to-exe#306] opened 2022-08-31 14:06 UTC
**Quick Checks For You**
- [x] I have read/searched in the [help post](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe)
- [x] I have [searched other issues](https://github.com/brentvollebregt/auto-py-to-exe/issues?q=is%3Aissue+) looking for an issue similar to mine
- [x] I have made sure my applicaiton/script runs before trying to package

**Describe the bug**
Failed to import config: application closes, browser window goes into infinite initialization

**To Reproduce**
1. Run auto-py-to-exe
2. Try to import config file
3. Infinity initializing

> If you have example code, please provide a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example).

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/40202917/187697285-814bb4a5-3f60-4b47-b563-432f9e2af13d.png)
![image](https://user-images.githubusercontent.com/40202917/187697314-84aa3872-b567-42cc-9457-c39849e106aa.png)

**Your Environment:**
- Python version (`python --version`): Python 3.10.6
- auto-py-to-exe version (`pip show auto-py-to-exe`): 2.22.0
- PyInstaller version (`pip show pyinstaller`): 5.3
- Eel version (`pip show eel`): 0.14.0

**Additional context**

**Comment by brentvollebregt** [comment] 2022-09-01 09:17
I just performed those reproduction steps and was unable to reproduce the issues. Is there a certain config file that makes this happen?

In terms of debugging, can you look at these for me:
- Open dev tools in the auto-py-to-exe UI (F12); is there anything in the console tab?
- Did the command in the terminal finish? Or is it still running?
- Is there any errors in the terminal?

**Comment by kapertdog** [comment] 2022-09-01 09:51
Happens to anyone config file
Entered again all the parameters manually, saved the config, loaded it, everything still the same

The problem appeared after updating auto-py-to-exe (don’t remember what version it was before)
Convertation still works
- See some errors in web console:
![image](https://user-images.githubusercontent.com/40202917/187882427-9d735e79-dfd9-483d-ae3d-23eed4282cea.png)
- Yes, command in the terminal stopped
![image](https://user-images.githubusercontent.com/40202917/187882653-e555017f-9269-4d83-92ea-732d4a3f7d03.png)
- No one error in terminal
- My config files: [my_configs.zip](https://github.com/brentvollebregt/auto-py-to-exe/files/9468759/my_configs.zip)

**Comment by brentvollebregt** [comment] 2022-09-01 09:58
Potentially 886bac6789113c10c16695802a5174b0c815d0af broke this. If you checkout 7b708cb59b53e4705cadc08c55c0921f3b020b6b, does this still happen?

**Comment by kapertdog** [comment] 2022-09-01 10:04
No, everything works on 2.21.0

**Comment by brentvollebregt** [comment] 2022-09-01 10:24
Sweet, so definitely is an issue with 886bac6789113c10c16695802a5174b0c815d0af then. The issue would be caused by when the config is loaded, the whole page reloads. Typically this works completely fine (like on my machine) but potentially yours may be loading slower for some reason.

Digging into Eel's source, I see that it calls `_shutdown = gvt.spawn_later(1.0, _detect_shutdown)` when a websocket disconnects - this makes the application wait 1 second to see if any more websockets are connected and if there are none, terminate.

Just as I was thinking of ways to get around this. I see ChrisKnott/Eel#529 was added recently - increasing this value should fix this issue! I'll drag it up to three seconds and get you to test the fix.

> Side note: That error is related to "userscript" and is not associated with this project

**Comment by brentvollebregt** [comment] 2022-09-24 11:06
Sorry for the delay on this - I have moved away from the reload-based import to clearing everything before importing the config.

The changes will be in 2.23.1 in a bit

**Closed by brentvollebregt** 2022-09-24 11:07 UTC
Labels: bug

**Comment by chaush-server** [comment] 2023-09-25 08:48
![image](https://github.com/brentvollebregt/auto-py-to-exe/assets/79080580/3a6cabe9-ccd8-4ca5-a1e8-de420d341dd3)
![image](https://github.com/brentvollebregt/auto-py-to-exe/assets/79080580/c7ce0c31-12b8-428a-8980-650a32255086)
![image](https://github.com/brentvollebregt/auto-py-to-exe/assets/79080580/d253dcbd-1fb7-4f5b-b3ff-62cf69a9e8b8)

**Comment by brentvollebregt** [comment] 2023-09-25 08:49
@chaush-server this was fixed in 2.40.0 - see #431

**Comment by chaush-server** [comment] 2023-09-25 08:50
wow so fast answer ty
