### ISSUE TITLE
A mess on the screen

### ISSUE THREAD

**Issue by limelect** [brentvollebregt/auto-py-to-exe#447] opened 2023-12-18 08:32 UTC
The screen is not OK
Those pictures are all over
Window 7

![Screenshot - 18_12_2023 , 10_30_54](https://github.com/brentvollebregt/auto-py-to-exe/assets/4199131/c3722ab0-aecd-4898-8197-ceb10850f91d)

**Comment by brentvollebregt** [comment] 2023-12-18 09:54
1. Are there any errors in the console you started auto-py-to-exe from?
2. Are there any errors in the DevTools console? (can right-click and inspect element in the window)
3. Are there any 404's in the network tab in DevTools?

**Comment by limelect** [comment] 2023-12-18 10:04
No Errors at all

**Comment by limelect** [comment] 2023-12-18 10:15
PS I made the same but taught with you I will have a better chance.
https://en.delphipraxis.net/topic/10675-d4p_export_demo/
and mine
https://limelect.com/downloads/python-2-execute/  with Delphi

**Comment by limelect** [comment] 2023-12-18 10:32
well I installed yours and this is what it does, it does not display as your picture shows
sorry for miss leading you

**Comment by brentvollebregt** [comment] 2023-12-18 10:37
> In the console you started auto-py-to-exe from - is the process still running, or has it ended? As in can you type characters in there and run commands or is the last one running stopping you.

**Comment by limelect** [comment] 2023-12-18 11:28
It is working but the pictures are in between the text. It does work with no problem.

**Comment by limelect** [comment] 2023-12-18 11:29
I have to leave now i will get in touch later

**Comment by limelect** [comment] 2023-12-18 19:00
I have put on my Dropbox a screen catch
This is what I have after pip install ....
Too large for put here

https://www.dropbox.com/s/f2ig3ri9hmd26xj/tst.zip?dl=0

**Comment by brentvollebregt** [comment] 2023-12-19 09:43
Yes, I understand the UI looks incorrect - this is most likely due to the stylesheet not loading.

Could you please check each of these and answer them individually:

1. Are there any errors or messages in the console you started auto-py-to-exe from? If so, what are they?
2. Are there any errors in the DevTools console? If so, what are they? (can right-click and inspect element in the window)
3. Are there any 404's in the network tab in DevTools? If so, what URLs 404ed?
4. In the console you started auto-py-to-exe from - is the process still running, or has it ended?

**Comment by limelect** [comment] 2023-12-19 10:18
1 2 3 NO
4 only 1 process
To sum it up no errors what so ever

**Comment by limelect** [comment] 2023-12-19 10:19
If you want i can let you go into my computer if it helps any

**Comment by brentvollebregt** [comment] 2023-12-20 06:50
In DevTools, are you seeing the CSS file being loaded?

![image](https://github.com/brentvollebregt/auto-py-to-exe/assets/19944838/b5719453-d924-49ec-834b-f604eed25776)

> If you want i can let you go into my computer if it helps any

We can discuss the issue here

> Do not forget all I did is pip

First I've heard (I see you cleared the template out) - thank you for letting me know

**Comment by limelect** [comment] 2023-12-20 08:59
Sorry i will leave the matter as my need is much more complicated
then your solution or mine
see
https://github.com/Embarcadero/DelphiFMX4Python/issues/94

**Comment by brentvollebregt** [comment] 2024-01-12 03:47
I'm going to close this in the meantime as I have nothing to work off here; no clean reproduction or error.

If anyone else has this issue, feel free to comment in this issue and we can re-open it.

**Closed by brentvollebregt** 2024-01-12 03:47 UTC
Labels: bug
