### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by badouzeum** [brentvollebregt/auto-py-to-exe#415] opened 2023-08-17 15:02 UTC
je veux Convertir un fichier python .py en éxecutable .exe avec le module python auto py to exe mais si j'assai d'ouvrir la librairie "auto py to exe" je recoi le message suivant: 
File "C:\Users\PRECISION\AppData\Roaming\Python\Python311\site-packages\greenlet\__init__.py", line 29, in <module>
    from ._greenlet import _C_API # pylint:disable=no-name-in-module
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: DLL load failed while importing _greenlet: Le module spécifié est introuvable.

**Comment by brentvollebregt** [comment] 2023-08-18 07:22
Duplicate of #325 - take a look at [this solution](https://github.com/brentvollebregt/auto-py-to-exe/issues/325#issuecomment-1313939303). Let me know if this doesn't work.

*By the way, searching "DLL load failed while importing _greenlet" in the issues in this repo would have pointed you to this*

**Closed by brentvollebregt** 2023-08-18 07:22 UTC
