### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by sharkmu** [brentvollebregt/auto-py-to-exe#271] opened 2022-05-13 19:06 UTC
hi! I made a simple program and i converted it into an exe with auto-py-to-exe. Than i checked on virustotal.com so is there any virus in it, and virustotal found trojan in it. So wtf

**Comment by brentvollebregt** [comment] 2022-05-14 06:03
Duplicate of #156

Please search previous issues before creating a new one. I searched for ["Virus"](https://github.com/brentvollebregt/auto-py-to-exe/issues?q=is%3Aissue+Virus) in this repo and it came back with 9 matches - a good majority of them being almost the same as this issue.

**Closed** 2022-05-14 06:03 UTC
