### ISSUE TITLE
'eel.chrome' has no attribute 'get_instance_path'

### ISSUE THREAD

**Issue by PyICoder** [brentvollebregt/auto-py-to-exe#77] opened 2019-11-02 23:02 UTC
Traceback (most recent call last):
  File "run.py", line 9, in <module>
    apte.run()  File "C:\Users\-------\Downloads\auto-py-to-exe-2.6.5\auto_py_to_exe\__main__.py", line 375, in run
    chrome_instance_path = eel.chrome.get_instance_path()AttributeError: module 'eel.chrome' has no attribute 'get_instance_path'

What causes this?

**Comment by brentvollebregt** [comment] 2019-11-03 00:36
What version of auto-py-to-exe and Eel do you have installed?

**Comment by PyICoder** [comment] 2019-11-04 01:24
Latest Versions, just installed Eel and auto-py-to-exe, it works when run by console (python -m auto_py_to_exe), not by running run.py

**Comment by brentvollebregt** [comment] 2019-11-04 01:46
I am unable to reproduce this error when executing `python run.py`. Could you please provide more details? 

I remember fixing this issue in a previously (3a08aeaa8b9eeae950cee9cd5f1bda168c7077cf) and enforcing that Eel 0.10.0 is used. 

I see that samuelhwilliams/Eel@42425c512577311053e1357cf96266b7f3fff55b changed `get_instance_path` to `find_path` (yet another breaking change made by them) but this would not affect this package as I explicitly state that Eel 0.10.0 must be used. Please make sure you are running Eel 0.10.0 as stated in [requirements.txt](https://github.com/brentvollebregt/auto-py-to-exe/blob/master/requirements.txt)

**Comment by brentvollebregt** [comment] 2019-11-13 20:05
This should be fixed in 2.6.6 for those that installed Eel 0.11.0 instead of the version stated in requirements.txt and setup.py

**Closed** 2019-11-14 04:33 UTC
