### ISSUE TITLE
[Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by Yoko11111111** [brentvollebregt/auto-py-to-exe#339] opened 2022-12-07 10:42 UTC
**Describe the bug**
Hello, wanted to convert my py to exe. But now im starting the exe and i get this message: [Errno 2] No such file or directory: 'C:\\Users\\Administrator\\AppData\\Local\\Temp\\2\\_MEI74002\\user_agent\\data/smartphone_dev_id.json'
[1776] Failed to execute script 'test' due to unhandled exception!

**To Reproduce**
cmd 
test.exe

> If you have example code, please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

Idk if that helps but i use user_agent only for this line of code:
            headers = user_agent.generate_navigator(os=None, navigator=None, platform=None, device_type=None)

**Expected behavior**
It should just work but its not even starting 

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/108374464/206157541-cac342b7-ba1c-4d93-bba9-adebbbde0786.png)

**Your Environment:**
- Python version 3.11.1
- auto-py-to-exe version 2.26.0
- PyInstaller version 5.7.0
- Eel version 0.14.0

**Additional context (optional)**
It scrapes html idk if this is relevant 

Hope you can help me.
love your work :)

**Comment by brentvollebregt** [comment] 2022-12-10 20:29
It looks like you are referencing a JSON file that doesn't exist. Either you have not included it or your reference is incorrect.

**Comment by Yoko11111111** [comment] 2022-12-12 06:36
I think you are right. I removed it now but now it is stuck at converting...

Last thing that shows is this and then its stuck
120930 INFO: Loading module hook 'hook-gevent.py' from 'C:\\Users\\jamu\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...

**Comment by brentvollebregt** [comment] 2022-12-13 05:39
Closing. Issue was maybe a basic path referencing issue- (not confirmed).

**Closed by brentvollebregt** 2022-12-13 05:39 UTC
Labels: question
