### ISSUE TITLE
Can't convert a second py file or reconvert original. 

### ISSUE THREAD

**Issue by ponceatl** [brentvollebregt/auto-py-to-exe#22] opened 2018-07-31 22:47 UTC
Great program. Worked perfectly on first py file. However I have not been able to get it to convert a second py file or reconvert original.  This is the output I get when trying:

Cleaning file structure
238042 INFO: PyInstaller: 3.4.dev0+7817d3fac
238042 INFO: Python: 3.6.4
238044 INFO: Platform: Windows-10-10.0.17134-SP0
Traceback (most recent call last):

  File "src\gevent\greenlet.py", line 716, in gevent._greenlet.Greenlet.run

  File "C:\Users\RHG2\AppData\Local\Programs\Python\Python36-32\lib\site-packages\eel\__init__.py", line 191, in _process_message
    return_val = _exposed_functions[message['name']](*message['args'])

  File "C:\Users\RHG2\Desktop\auto-py-to-exe-master\run.py", line 165, in convert
    pyi.run() # Execute PyInstaller

  File "C:\Users\RHG2\AppData\Local\Programs\Python\Python36-32\lib\site-packages\PyInstaller\__main__.py", line 109, in run
    spec_file = run_makespec(**vars(args))

  File "C:\Users\RHG2\AppData\Local\Programs\Python\Python36-32\lib\site-packages\PyInstaller\__main__.py", line 56, in run_makespec
    spec_file = PyInstaller.building.makespec.main(filenames, **opts)

  File "C:\Users\RHG2\AppData\Local\Programs\Python\Python36-32\lib\site-packages\PyInstaller\building\makespec.py", line 430, in main
    specfile = open(specfnm, 'w')

PermissionError: [Errno 13] Permission denied: 'C:\\WINDOWS\\system32\\manual_start.spec'

2018-07-31T22:33:10Z
<Greenlet "Greenlet-0" at 0x4d26140: _process_message({'call': 7.153385102862373, 'name': 'convert', 'ar, <geventwebsocket.websocket.WebSocket object at 0x0)> failed with PermissionError

**Comment by brentvollebregt** [comment] 2018-08-01 03:38
Your current directory is in system32 and you have no permissions. Maybe try giving it some permissions if you want to modify data in this directory?

**Comment by brentvollebregt** [comment] 2018-08-02 09:16
Did this fix the issue or is it still there?

**Comment by ponceatl** [comment] 2018-08-02 10:55
Setting permissions didn't work. But I found another solution. Will message
later. At airport now.

**Comment by brentvollebregt** [comment] 2018-10-10 03:42
It has been three months since this issue has been opened with no further movement.

No information has been given on how to reproduce this issue and by the PermissionError reported in the traceback, it seems like the user has not given necessary permissions to allow this script to run in the current working directory (which in this case was System32).

I will close this issue, but if more information is given or an error similar to this is still occurring, I will be happy to take a look at it.

**Closed by brentvollebregt** 2018-10-10 03:42 UTC
Labels: question
