### ISSUE TITLE
Maleware detected on output executable file

### ISSUE THREAD

**Issue by BluelyTASer** [brentvollebregt/auto-py-to-exe#156] opened 2021-02-06 21:38 UTC
Is that true that you did that to us? 🤔
![236](https://user-images.githubusercontent.com/59511669/107130258-6ef1c700-68aa-11eb-8e0b-d3be7afb9e6a.PNG)

**Comment by brentvollebregt** [comment] 2021-02-06 22:15
Did you look at previous issues that talk about this? #122 and #125 are very similar.

Has been raised in the PyInstaller repo at pyinstaller/pyinstaller#4633 and the [same message is given](https://github.com/pyinstaller/pyinstaller/issues/4633#issuecomment-575537881):

> Please contact you anti-virus vendor. There is nothing we can do about this false positive.
> 
> If your anti-virus vendor considers one of the files included in the PyInstaller distribution or a file generated by PyInstaller to be malicious, there is nothing we can do about this. Even if we'd change our code, they'd change their pattern and the race starts again.
> 
> See this [mailing-list thread](http://www.mail-archive.com/pyinstaller@googlegroups.com/msg05002.html) and [other tickets for his topic](https://github.com/pyinstaller/pyinstaller/issues?q=is%3Aissue+virus+is%3Aclosed).

You literally have access to the source code of auto-py-to-exe and can even look at the source of it on your own machine after getting it from PyPI. Did you look at that before raising this? Where is your evidence aside from a false positive?

To be honest, that title is quite rule in my opinion.

**Comment by brentvollebregt** [comment] 2021-02-06 22:17
Closing as this is a duplicate of #122.

If you do find some supporting evidence that I have done something malicious in this project - feel free to comment here as I would love to hear it.

**Closed** 2021-02-06 22:17 UTC
Labels: duplicate
