### ISSUE TITLE
new problem :(

### ISSUE THREAD

**Issue by souriens253** [brentvollebregt/auto-py-to-exe#41] opened 2019-01-02 07:52 UTC
Hi brent sorry i try to look in your blog for a solution  but i get this problem
if you can help me 
thank you

`Building in the current instances temporary directory at C:\Users\user\AppData\Local\Temp\tmp4rkm3kpv
To get a new temporary directory, restart this application
Executing: pyinstaller -y -F -w "C:/Users/user/Music/prog.py"
3262493 INFO: PyInstaller: 3.4
3262493 INFO: Python: 3.7.2
3262493 INFO: Platform: Windows-10-10.0.17134-SP0
3262495 INFO: wrote C:\Users\user\AppData\Local\Temp\tmp4rkm3kpv\prog.spec
3262497 INFO: UPX is not available.
3262498 INFO: Extending PYTHONPATH with paths
['C:\\Users\\user\\Music',
 'C:\\Users\\user\\AppData\\Local\\Temp\\tmp4rkm3kpv']
3262498 INFO: checking Analysis
3262499 INFO: Building Analysis because Analysis-03.toc is non existent
3262499 INFO: Initializing module dependency graph...
3262501 INFO: Initializing module graph hooks...
3262504 INFO: Analyzing base_library.zip ...
3265746 INFO: running Analysis Analysis-03.toc
3265748 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Users\user\AppData\Local\Programs\Python\Python37-32\python.exe
3265820 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of C:\Users\user\AppData\Local\Programs\Python\Python37-32\python.exe
3265882 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of C:\Users\user\AppData\Local\Programs\Python\Python37-32\python.exe
3265943 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Users\user\AppData\Local\Programs\Python\Python37-32\python.exe
3266004 WARNING: lib not found: api-ms-win-crt-locale-l1-1-0.dll dependency of C:\Users\user\AppData\Local\Programs\Python\Python37-32\python.exe
3266072 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of C:\Users\user\AppData\Local\Programs\Python\Python37-32\python.exe
3266277 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of C:\Users\user\AppData\Local\Programs\Python\Python37-32\python37.dll
3266340 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of C:\Users\user\AppData\Local\Programs\Python\Python37-32\python37.dll
3266403 WARNING: lib not found: api-ms-win-crt-process-l1-1-0.dll dependency of C:\Users\user\AppData\Local\Programs\Python\Python37-32\python37.dll
3266463 WARNING: lib not found: api-ms-win-crt-filesystem-l1-1-0.dll dependency of C:\Users\user\AppData\Local\Programs\Python\Python37-32\python37.dll
3266532 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Users\user\AppData\Local\Programs\Python\Python37-32\python37.dll
3266594 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of C:\Users\user\AppData\Local\Programs\Python\Python37-32\python37.dll
3266662 WARNING: lib not found: api-ms-win-crt-locale-l1-1-0.dll dependency of C:\Users\user\AppData\Local\Programs\Python\Python37-32\python37.dll
3266724 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of C:\Users\user\AppData\Local\Programs\Python\Python37-32\python37.dll
3266789 WARNING: lib not found: api-ms-win-crt-environment-l1-1-0.dll dependency of C:\Users\user\AppData\Local\Programs\Python\Python37-32\python37.dll
3266853 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of C:\Users\user\AppData\Local\Programs\Python\Python37-32\python37.dll
3266919 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of C:\Users\user\AppData\Local\Programs\Python\Python37-32\python37.dll
3266984 WARNING: lib not found: api-ms-win-crt-conio-l1-1-0.dll dependency of C:\Users\user\AppData\Local\Programs\Python\Python37-32\python37.dll
3267054 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of C:\Users\user\AppData\Local\Programs\Python\Python37-32\VCRUNTIME140.dll
3267115 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of C:\Users\user\AppData\Local\Programs\Python\Python37-32\VCRUNTIME140.dll
3267176 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Users\user\AppData\Local\Programs\Python\Python37-32\VCRUNTIME140.dll
3267244 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of C:\Users\user\AppData\Local\Programs\Python\Python37-32\VCRUNTIME140.dll
3267310 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of C:\Users\user\AppData\Local\Programs\Python\Python37-32\VCRUNTIME140.dll
3267313 INFO: Caching module hooks...
3267320 INFO: Analyzing C:\Users\user\Music\prog.py

Syntax error in
C:\Users\user\Music\prog.py
  File "C:\Users\user\Music\prog.py", line 43
    print "Handled exception:\n"+str(e)
                               ^
SyntaxError: invalid syntax
An error occurred, traceback follows:
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PyInstaller\depend\analysis.py", line 201, in run_script
    self._top_script_node = super(PyiModuleGraph, self).run_script(pathname)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1344, in run_script
    co_ast = compile(contents, pathname, 'exec', ast.PyCF_ONLY_AST, True)
  File "C:\Users\user\Music\prog.py", line 43
    print "Handled exception:\n"+str(e)
                               ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Desktop\auto-py-to-exe-master\auto-py-to-exe-master\auto_py_to_exe\__main__.py", line 215, in convert
    pyi.run() # Execute PyInstaller
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PyInstaller\building\build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PyInstaller\building\build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 17, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PyInstaller\building\build_main.py", line 241, in __init__
    self.__postinit__()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PyInstaller\building\build_main.py", line 443, in assemble
    priority_scripts.append(self.graph.run_script(script))
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PyInstaller\depend\analysis.py", line 206, in run_script
    raise SystemExit(1)
SystemExit: 1

Project output will not be moved to output folder
Complete.
`

**Comment by brentvollebregt** [comment] 2019-01-02 19:11
I'm sorry but I cannot see the issue with auto-py-to-exe in this output; could you please tell me what the issue is with auto-py-to-exe?

**Comment by souriens253** [comment] 2019-01-03 03:43
i have no probleme to start auto py but after when i try to covert the files i get this issue

**Comment by brentvollebregt** [comment] 2019-01-03 03:49
> when i try to covert the files i get this issue

Is it only for these files or all your files?

Looking at this output, you can see that you're getting a `SyntaxError` on line 43 in the file `C:\Users\user\Music\prog.py`. Have you actually executed this file with Python 3 before? If you had, you would have seen this error before in your script.

**Comment by brentvollebregt** [comment] 2019-01-03 03:54
Closing due to the fact that this SyntaxError was happening in the user's script and could have easily been seen if they had executed the script with Python 3 (which was being used to package the script file).

If you feel I have missed something, feel free to say and we can investigate this further.

**Closed by brentvollebregt** 2019-01-03 03:54 UTC
Labels: invalid
