### ISSUE TITLE
Virus in auto-py-to-exe?

### ISSUE THREAD

**Issue by K3yr0nym0us** [brentvollebregt/auto-py-to-exe#289] opened 2022-07-20 23:55 UTC
**Describe the bug**

**Expected behavior**

**To Reproduce**

**My Platform**

**Additional context**

**Comment by brentvollebregt** [comment] 2022-07-21 00:28
Duplicate of #122.

Please read the help post and do a basic search in previous issues before creating an issue next time.

**Closed** 2022-07-21 00:31 UTC
Labels: duplicate
